Create ordered point cloud (issue #126)
ros/common_msgs pull request #157
Opened 2020-01-20 15:27 UTC by Hi-Zed

Small changes to create_cloud in point_cloud2.py to support ordered point clouds with specific height and width.

2020-01-21 02:13 UTC, haudren commented
Thanks for the patch, it looks straightforward and a good addition. I hope this can get merged!

2020-01-23 02:07 UTC, tfoote requested changes
This looks reasonable. Though it needs a little bit more error handling. None times an int will except.

2020-01-23 02:07 UTC, tfoote commented on sensor_msgs/src/sensor_msgs/point_cloud2.py
> +    if height == 1:
This looks like it will have problems if height is non unary but width is defaulted to None. Some other checks are going to be necessary.

2020-01-23 02:07 UTC, tfoote commented on sensor_msgs/src/sensor_msgs/point_cloud2.py
> +    point_step = cloud_struct.size
These intermediate values appear to only be used once so are probably not worth creating at all.

2020-01-23 12:11 UTC, Hi-Zed commented on sensor_msgs/src/sensor_msgs/point_cloud2.py
> +    if height == 1:
I'll add a check on both height and width.
The original implementation didn't perform any check on header, fields and points, for example, if they are empty. Do you want me to add something like that?

2020-01-30 02:30 UTC, tfoote commented on sensor_msgs/src/sensor_msgs/point_cloud2.py
> +    if height == 1:
I was mostly worried about the default values messing things up. Though a little bit of sanitizing would be valuable. But we need to be careful about what error response behavior is caused by invalid data.

2020-01-30 02:32 UTC, tfoote reviewed
Thanks for the update that looks better. Could you also write some basic unit tests. It would be good to add some that assert the ordering that this implements stays valid. As well as can validate the error handling. And it appears that we don't have any python unit tests for this at all.

2025-04-25 21:33 UTC, closed without merging

2025-04-25 21:33 UTC, sloretz commented
Thank you for the PR!

Unfortunately I don't think we should merge this one.

[ROS Noetic will reach end-of-life on May 31st, 2025](https://discourse.ros.org/t/ros-noetic-end-of-life-may-31-2025/43160). Every change comes with a risk of introducing regressions, and there isn't much time left to fix them. I'm closing pull requests that add features so that the remaining time is allocated towards bug fixes and compatibility with newer Ubuntu distros.